# Server
server.port=8080

# SQL Server (Docker)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookreview_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Qq147898@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
# ⚠️ VULN: vẫn là weak secret nhưng đủ độ dài để chạy
app.jwt.secret=secret123secret123secret123secret1
app.jwt.expiration=86400000

# Hiển thị lỗi chi tiết
# ⚠️ VULN: lộ stack trace ra ngoài
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

# Spring Security Filter Order (Spring Boot 4.x)
spring.security.filter.order=10